#!/bin/sh

echo "----- PART 1: library a -----"
echo "% cd ./libraries/a"
cd ./libraries/a
echo "% g++ -Wall -Werror -fPIC -shared ../../interface.cpp a.cpp -o a.so"
g++ -Wall -Werror -std=c++11 -fPIC -shared ../../interface.cpp a.cpp -o a.so
echo "% cd ../../"
cd ../../
echo ""

echo "----- PART 2: library b -----"
echo "% cd ./libraries/b"
cd ./libraries/b
echo "% g++ -Wall -Werror -fPIC -shared ../../interface.cpp b.cpp -o b.so"
g++ -Wall -Werror -std=c++11 -fPIC -shared ../../interface.cpp b.cpp -o b.so
echo "% cd ../../"
cd ../../
echo ""

echo "----- PART 3: program -----"
echo "% g++ -Wall -Werror -std=c++11 interface.cpp plugin.cpp plugin_list.cpp main.cpp -ldl -o prog"
g++ -Wall -Werror -std=c++11 interface.cpp plugin.cpp plugin_list.cpp main.cpp -ldl -o prog
