#!/bin/sh

echo "----- PART 1: library a -----"
echo "% cd ./libraries/a"
cd ./libraries/a
echo "% g++ -Wall -Werror -fPIC -shared ../../interface.cpp a.cpp -o a.so"
g++ -Wall -Werror -std=c++11 -fPIC -shared ../../interface.cpp a.cpp -o a.so
echo "% cd ../../"
cd ../../
echo ""

echo "----- PART 2: program -----"
echo "% g++ -Wall -Werror -std=c++11 main.cpp -ldl -o prog"
g++ -Wall -Werror -std=c++11 interface.cpp plugin.cpp main.cpp -ldl -o prog
